import type { MerchantRule } from './types';

/**
 * Curated Malaysian Subscription Catalog (§2.1).
 *
 * 100% deterministic, zero-AI lookup catalog mapping noisy bank descriptors
 * to canonical names, domains, categories, and student discount plans.
 */
export const MALAYSIAN_SUBSCRIPTION_CATALOG: readonly MerchantRule[] = [
  // 1. Streaming & Music
  {
    id: 'spotify',
    canonicalName: 'Spotify',
    domain: 'spotify.com',
    category: 'Entertainment',
    aliases: [/sptf/i, /spotify/i],
    studentPlan: {
      standardMonthlySen: 1590,
      studentMonthlySen: 850,
      planName: 'Spotify Premium Student',
      requirement: 'SheerID university student status',
      dealUrl: 'https://www.spotify.com/my-en/student/',
    },
  },
  {
    id: 'apple_music',
    canonicalName: 'Apple Music',
    domain: 'apple.com',
    category: 'Entertainment',
    aliases: [/apple\.com\/bill/i, /itunes/i, /apple\s*music/i],
    studentPlan: {
      standardMonthlySen: 1690,
      studentMonthlySen: 890,
      planName: 'Apple Music Student (includes Apple TV+)',
      requirement: 'UNiDAYS student verification',
      dealUrl: 'https://www.apple.com/my/apple-music/',
    },
  },
  {
    id: 'youtube_premium',
    canonicalName: 'YouTube Premium',
    domain: 'youtube.com',
    category: 'Entertainment',
    aliases: [/youtube.*prem/i, /googletempo/i, /google.*yt/i, /youtube/i],
    studentPlan: {
      standardMonthlySen: 2090,
      studentMonthlySen: 1290,
      planName: 'YouTube Student Membership',
      requirement: 'SheerID student status',
      dealUrl: 'https://www.youtube.com/premium/student',
    },
  },
  {
    id: 'netflix',
    canonicalName: 'Netflix',
    domain: 'netflix.com',
    category: 'Entertainment',
    aliases: [/nflx/i, /netflix/i],
  },
  {
    id: 'disney_hotstar',
    canonicalName: 'Disney+ Hotstar',
    domain: 'hotstar.com',
    category: 'Entertainment',
    aliases: [/hotstar/i, /disney/i],
  },
  {
    id: 'amazon_prime',
    canonicalName: 'Amazon Prime Video',
    domain: 'primevideo.com',
    category: 'Entertainment',
    aliases: [/prime\s*video/i, /amazon\s*prime/i, /amzn\s*prime/i],
    studentPlan: {
      standardMonthlySen: 2500,
      studentMonthlySen: 1250,
      planName: 'Prime Student (50% Off)',
      requirement: 'Prime Student university status verification',
      dealUrl: 'https://www.amazon.com/joinstudent',
    },
  },
  {
    id: 'astro',
    canonicalName: 'Astro',
    domain: 'astro.com.my',
    category: 'Entertainment',
    aliases: [/astro/i, /measat/i],
  },
  {
    id: 'viu',
    canonicalName: 'Viu',
    domain: 'viu.com',
    category: 'Entertainment',
    aliases: [/viu/i, /pccw\s*viu/i],
  },
  {
    id: 'iqiyi',
    canonicalName: 'iQiyi',
    domain: 'iq.com',
    category: 'Entertainment',
    aliases: [/iqiyi/i],
  },
  {
    id: 'wetv',
    canonicalName: 'WeTV',
    domain: 'wetv.vip',
    category: 'Entertainment',
    aliases: [/wetv/i, /tencent\s*video/i],
  },
  {
    id: 'crunchyroll',
    canonicalName: 'Crunchyroll',
    domain: 'crunchyroll.com',
    category: 'Entertainment',
    aliases: [/crunchyroll/i],
  },
  {
    id: 'hbo_go',
    canonicalName: 'HBO GO',
    domain: 'hbogoasia.my',
    category: 'Entertainment',
    aliases: [/hbo\s*go/i, /hbo\s*max/i, /warner\s*media/i],
  },

  // 2. Malaysian Telcos & Broadband
  {
    id: 'unifi',
    canonicalName: 'Unifi Broadband',
    domain: 'unifi.com.my',
    category: 'Utilities',
    aliases: [/telekom\s*malaysia/i, /tm\s*bill/i, /unifi/i, /tm\s*unifi/i],
  },
  {
    id: 'maxis',
    canonicalName: 'Maxis / Hotlink',
    domain: 'maxis.com.my',
    category: 'Telecommunications',
    aliases: [/maxis/i, /hotlink/i],
    studentPlan: {
      standardMonthlySen: 3500,
      studentMonthlySen: 2500,
      planName: 'Hotlink Pakej Belia (RM 10 Monthly Cashback)',
      requirement: 'Youth age 18–24 registration in Hotlink app',
      dealUrl: 'https://www.hotlink.com.my',
    },
  },
  {
    id: 'celcomdigi',
    canonicalName: 'CelcomDigi',
    domain: 'celcomdigi.com',
    category: 'Telecommunications',
    aliases: [/celcom/i, /digi\s*tele/i, /celcomdigi/i, /digi/i],
    studentPlan: {
      standardMonthlySen: 6000,
      studentMonthlySen: 4000,
      planName: 'CelcomDigi Pakej Belia (RM 20 Rebate)',
      requirement: 'Malaysian youth/student age 18–24 MyKad verification',
      dealUrl: 'https://www.celcomdigi.com/promotions/pakej-belia',
    },
  },
  {
    id: 'u_mobile',
    canonicalName: 'U Mobile',
    domain: 'u.com.my',
    category: 'Telecommunications',
    aliases: [/u\s*mobile/i, /umobile/i],
    studentPlan: {
      standardMonthlySen: 3800,
      studentMonthlySen: 2800,
      planName: 'U Postpaid 38 Belia Rebate',
      requirement: 'Tertiary student ID or age 18–24 MyKad',
      dealUrl: 'https://www.u.com.my',
    },
  },
  {
    id: 'yes_5g',
    canonicalName: 'Yes 5G (YTL)',
    domain: 'yes.my',
    category: 'Telecommunications',
    aliases: [/ytl\s*comm/i, /yes\s*5g/i, /yes\s*comm/i],
    studentPlan: {
      standardMonthlySen: 3000,
      studentMonthlySen: 2000,
      planName: 'Yes 5G Pelajar / Siswa (Unlimited 5G)',
      requirement: 'Student card / university enrollment verification',
      dealUrl: 'https://www.yes.my',
    },
  },
  {
    id: 'time_internet',
    canonicalName: 'TIME Internet',
    domain: 'time.com.my',
    category: 'Telecommunications',
    aliases: [/time\s*dotcom/i, /time\s*fibre/i, /time\s*internet/i],
  },

  // 3. Malaysian Utilities & E-Wallets (Subscription / Recurring plans)
  {
    id: 'tnb',
    canonicalName: 'TNB (Tenaga Nasional)',
    domain: 'mytnb.com.my',
    category: 'Utilities',
    aliases: [/tenaga\s*nasional/i, /tnb\s*bill/i, /mytnb/i],
  },
  {
    id: 'air_selangor',
    canonicalName: 'Air Selangor',
    domain: 'airselangor.com',
    category: 'Utilities',
    aliases: [/air\s*selangor/i, /syabas/i],
  },
  {
    id: 'indah_water',
    canonicalName: 'Indah Water',
    domain: 'iwk.com.my',
    category: 'Utilities',
    aliases: [/indah\s*water/i, /iwk/i],
  },
  {
    id: 'touch_n_go',
    canonicalName: "Touch 'n Go Autopay",
    domain: 'touchngo.com.my',
    category: 'Utilities',
    aliases: [/tng\s*autopay/i, /touch\s*n\s*go\s*auto/i],
  },
  {
    id: 'grab',
    canonicalName: 'GrabUnlimited',
    domain: 'grab.com',
    category: 'Utilities',
    aliases: [/grabunlimited/i, /grab\s*unlimited/i, /grab.*subscription/i],
  },
  {
    id: 'foodpanda',
    canonicalName: 'pandapro',
    domain: 'foodpanda.my',
    category: 'Utilities',
    aliases: [/pandapro/i, /foodpanda.*pro/i, /foodpanda.*subscription/i],
  },

  // 4. Software, AI & Productivity
  {
    id: 'chatgpt',
    canonicalName: 'ChatGPT Plus',
    domain: 'openai.com',
    category: 'Software',
    aliases: [/openai/i, /chatgpt/i],
  },
  {
    id: 'claude',
    canonicalName: 'Claude Pro',
    domain: 'anthropic.com',
    category: 'Software',
    aliases: [/claude/i, /anthropic/i],
  },
  {
    id: 'midjourney',
    canonicalName: 'Midjourney',
    domain: 'midjourney.com',
    category: 'Software',
    aliases: [/midjourney/i],
  },
  {
    id: 'canva',
    canonicalName: 'Canva Pro',
    domain: 'canva.com',
    category: 'Software',
    aliases: [/canva/i],
    studentPlan: {
      standardMonthlySen: 2990,
      studentMonthlySen: 0,
      planName: 'Canva for Education / Students',
      requirement: 'Verified university student email (.edu.my)',
      dealUrl: 'https://www.canva.com/education/students/',
    },
  },
  {
    id: 'github_copilot',
    canonicalName: 'GitHub Copilot / Pro',
    domain: 'github.com',
    category: 'Software',
    aliases: [/github/i],
    studentPlan: {
      standardMonthlySen: 4500,
      studentMonthlySen: 0,
      planName: 'GitHub Student Developer Pack (Free Copilot & Pro)',
      requirement: 'GitHub Student Pack verification with student ID',
      dealUrl: 'https://education.github.com/pack',
    },
  },
  {
    id: 'notion',
    canonicalName: 'Notion Plus',
    domain: 'notion.so',
    category: 'Software',
    aliases: [/notion/i],
    studentPlan: {
      standardMonthlySen: 4500,
      studentMonthlySen: 0,
      planName: 'Notion for Education (Free Plus Plan)',
      requirement: 'Sign up with .edu.my student email',
      dealUrl: 'https://www.notion.so/product/notion-for-education',
    },
  },
  {
    id: 'adobe_cc',
    canonicalName: 'Adobe Creative Cloud',
    domain: 'adobe.com',
    category: 'Software',
    aliases: [/adobe/i],
    studentPlan: {
      standardMonthlySen: 26000,
      studentMonthlySen: 8500,
      planName: 'Adobe Students & Teachers 60%+ Off',
      requirement: 'Institutional student email verification',
      dealUrl: 'https://www.adobe.com/my/creativecloud/buy/students.html',
    },
  },
  {
    id: 'icloud',
    canonicalName: 'iCloud+',
    domain: 'apple.com',
    category: 'Software',
    aliases: [/icloud/i, /apple\s*storage/i, /apple\.com\/bill/i],
  },
  {
    id: 'google_one',
    canonicalName: 'Google One',
    domain: 'google.com',
    category: 'Software',
    aliases: [/google\s*storage/i, /google\s*one/i, /google\s*gsuite/i, /google\s*workspace/i],
  },
  {
    id: 'microsoft_365',
    canonicalName: 'Microsoft 365',
    domain: 'microsoft.com',
    category: 'Software',
    aliases: [/microsoft/i, /office\s*365/i, /msft/i],
    studentPlan: {
      standardMonthlySen: 2700,
      studentMonthlySen: 0,
      planName: 'Microsoft 365 Education (Free Office Apps)',
      requirement: 'Sign up with valid .edu.my student email',
      dealUrl: 'https://www.microsoft.com/en-my/education/products/office',
    },
  },
  {
    id: 'figma',
    canonicalName: 'Figma',
    domain: 'figma.com',
    category: 'Software',
    aliases: [/figma/i],
    studentPlan: {
      standardMonthlySen: 6500,
      studentMonthlySen: 0,
      planName: 'Figma for Education (Free Professional Plan)',
      requirement: 'Student application form with school email',
      dealUrl: 'https://www.figma.com/education/',
    },
  },
  {
    id: 'jetbrains',
    canonicalName: 'JetBrains',
    domain: 'jetbrains.com',
    category: 'Software',
    aliases: [/jetbrains/i, /intellij/i, /pycharm/i, /webstorm/i],
    studentPlan: {
      standardMonthlySen: 12000,
      studentMonthlySen: 0,
      planName: 'JetBrains Free Student Pack (All IDEs)',
      requirement: 'University email or ISIC student card',
      dealUrl: 'https://www.jetbrains.com/community/education/#students',
    },
  },
  {
    id: 'slack',
    canonicalName: 'Slack',
    domain: 'slack.com',
    category: 'Software',
    aliases: [/slack/i],
  },
  {
    id: 'zoom',
    canonicalName: 'Zoom',
    domain: 'zoom.us',
    category: 'Software',
    aliases: [/zoom/i],
  },

  // 5. Fitness, Wellness & Education
  {
    id: 'anytime_fitness',
    canonicalName: 'Anytime Fitness',
    domain: 'anytimefitness.my',
    category: 'Fitness',
    aliases: [/anytime\s*fit/i, /anytime\s*fitness/i],
  },
  {
    id: 'fitness_first',
    canonicalName: 'Fitness First',
    domain: 'fitnessfirst.com.my',
    category: 'Fitness',
    aliases: [/fitness\s*first/i],
  },
  {
    id: 'celebrity_fitness',
    canonicalName: 'Celebrity Fitness',
    domain: 'celebrityfitness.com.my',
    category: 'Fitness',
    aliases: [/celebrity\s*fit/i],
  },
  {
    id: 'classpass',
    canonicalName: 'ClassPass',
    domain: 'classpass.com',
    category: 'Fitness',
    aliases: [/classpass/i],
  },
  {
    id: 'headspace',
    canonicalName: 'Headspace',
    domain: 'headspace.com',
    category: 'Fitness',
    aliases: [/headspace/i],
    studentPlan: {
      standardMonthlySen: 3500,
      studentMonthlySen: 490,
      planName: 'Headspace Student Plan (85% Off)',
      requirement: 'SheerID university student status',
      dealUrl: 'https://www.headspace.com/student-plan',
    },
  },
  {
    id: 'duolingo',
    canonicalName: 'Duolingo Super',
    domain: 'duolingo.com',
    category: 'Education',
    aliases: [/duolingo/i],
    studentPlan: {
      standardMonthlySen: 2890,
      studentMonthlySen: 1445,
      planName: 'Duolingo Super Student (50% Off)',
      requirement: 'UNiDAYS student verification',
      dealUrl: 'https://www.myunidays.com',
    },
  },
  {
    id: 'strava',
    canonicalName: 'Strava Subscription',
    domain: 'strava.com',
    category: 'Fitness',
    aliases: [/strava/i],
  },
];
